apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  selector:
    matchLabels:
      run: trips
  replicas: 1
  template:
    metadata:
      labels:
        run: trips
    spec:
      containers:
      - name: trips
        image: registrylow2253.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: "sqladminlOw2253"
        - name: SQL_PASSWORD
          value: "Password123@"
        - name: SQL_SERVER
          value: "sqlserverlow2253.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0" 
        - name: WEB_PORT
          value: "80"
