apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
    role: backend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: trips
