kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-g
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-g
subjects:
- kind: Group
  namespace: api
  name: 8b03a097-25cb-434f-ae4a-d3b6702795f2

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-g
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-r
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-r
subjects:
- kind: Group
  namespace: api
  name: ae4d9211-31a9-444c-bd42-b0e7a449f974

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-r
  namespace: api
rules:
- apiGroups: [""]
  resources:
  - deployments
  - replicaSets
  - pods
  - services
  - cronjobs
  - jobs
  - ingress
  verbs:
  - get
  - watch
  - list
