apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrylow2253.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: "sqladminlOw2253"
        - name: SQL_PASSWORD
          value: "Password123@"
        - name: SQL_SERVER
          value: "sqlserverlow2253.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: CONFIG_FILES_PATH
          value: /secrets
        - name: WEB_PORT
          value: "80"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
