apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
  labels:
    app: tripviewer
    role: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: tripviewer
