apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
  labels:
    app: user-java
    role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
        role: backend
    spec:
      containers:
      - name: user-java
        image: registrylow2253.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: SQL_SERVER
          value: "sqlserverlow2253.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: SQLUSER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: SQLPASSWORD
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "tripviewer-secrets"
