# This is a SecretProviderClass example using user-assigned identity to access Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: tripviewer-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "34736196-56f9-4a38-b5b1-db66a5b0acb0"
    keyvaultName: "openhacksecrets"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: "8b802adc-b969-44f8-b0f6-18d54637bd27"                 # the tenant ID of the KeyVault 